apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-calico
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: local-services
  source:
    repoURL: https://projectcalico.docs.tigera.io/charts
    chart: tigera-operator
    targetRevision: v3.22.0
    helm:
      values: |
        installation:
          kubernetesProvider: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: calico-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  # ignoreDifferences:
  #   - group: rbac.authorization.k8s.io
  #     kind: ClusterRole
  #     name: local-amb-edge-stack
  #     jsonPointers:
  #     - /rules
  #   - group: rbac.authorization.k8s.io
  #     kind: ClusterRole
  #     name: local-amb-edge-stack-agent
  #     jsonPointers:
  #     - /rules
