apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-ambassador-custom
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: local-services
  source:
    repoURL: git@github.com:robcarmo/local-services.git
    targetRevision: HEAD
    path: ambassador/extra-config
  destination:
    server: https://kubernetes.default.svc
    namespace: ambassador
