---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: basic-http-listener
  namespace: ambassador
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
