---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: basic-https-listener  
  namespace: ambassador
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL