---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: ambassador
  namespace: ambassador
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route