apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  project: local-services
  source:
    repoURL: git@github.com:robcarmo/istio.git
    path: manifests/charts/base
    targetRevision: 1.13.1
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
